// One-off: download self-hosted woff2 subsets from Google Fonts into public/fonts/
// and emit public/fonts/fonts.css with url() rewritten to local /fonts/ paths.
// Keeps Google's per-script unicode-range subsetting (so the Bengali block only
// downloads when Bengali glyphs are actually used).
//
//   node scripts/fetch-fonts.mjs
//
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, '../public/fonts');

// A recent Chrome UA so Google serves woff2 (older UAs get ttf).
const UA =
	'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const FAMILIES = [
	{ slug: 'special-elite', ship: true, url: 'https://fonts.googleapis.com/css2?family=Special+Elite&display=swap' },
	{ slug: 'cutive-mono', ship: true, url: 'https://fonts.googleapis.com/css2?family=Cutive+Mono&display=swap' },
	{ slug: 'noto-serif-bengali', ship: true, url: 'https://fonts.googleapis.com/css2?family=Noto+Serif+Bengali:wght@400;700&display=swap' },
	// Specimen-only alternatives (Phase 1 item 2b) — evaluated, not shipped.
	{ slug: 'tiro-bangla', ship: false, url: 'https://fonts.googleapis.com/css2?family=Tiro+Bangla:ital@0;1&display=swap' },
	{ slug: 'baloo-da-2', ship: false, url: 'https://fonts.googleapis.com/css2?family=Baloo+Da+2:wght@400;700&display=swap' },
];

await mkdir(OUT_DIR, { recursive: true });

const header = '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n';
let shipCss = header;
let specimenCss = header + '/* Specimen-only faces (Phase 1 item 2b) — not loaded in production. */\n';

for (const fam of FAMILIES) {
	const res = await fetch(fam.url, { headers: { 'User-Agent': UA } });
	if (!res.ok) throw new Error(`CSS fetch failed for ${fam.slug}: ${res.status}`);
	let css = await res.text();

	// Download every referenced woff2 and rewrite its url() to a local path.
	const urls = [...css.matchAll(/url\((https:\/\/[^)]+\.woff2)\)/g)].map((m) => m[1]);
	let i = 0;
	for (const u of [...new Set(urls)]) {
		const name = `${fam.slug}-${String(i++).padStart(2, '0')}.woff2`;
		const bin = await fetch(u, { headers: { 'User-Agent': UA } });
		if (!bin.ok) throw new Error(`woff2 fetch failed ${u}: ${bin.status}`);
		await writeFile(resolve(OUT_DIR, name), Buffer.from(await bin.arrayBuffer()));
		css = css.split(u).join(`/fonts/${name}`);
	}

	const block = `\n/* ${fam.slug} */\n${css.trim()}\n`;
	if (fam.ship) shipCss += block;
	else specimenCss += block;
	console.log(`${fam.slug}: ${new Set(urls).size} file(s)${fam.ship ? '' : ' (specimen)'}`);
}

await writeFile(resolve(OUT_DIR, 'fonts.css'), shipCss);
await writeFile(resolve(OUT_DIR, 'fonts-specimen.css'), specimenCss);
console.log('Wrote public/fonts/fonts.css and fonts-specimen.css');
